repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
        exclude: ^dist/
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: no-commit-to-branch
      - id: trailing-whitespace
        exclude: ^dist/
        args:
          - --markdown-linebreak-ext=md
